version: "3.9"

services:
  db:
    image: xdubruille/woody_database:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    networks:
      - woody_net
    deploy:
      restart_policy:
        condition: any

  api:
    image: xdubruille/woody_api:latest
    restart: always
    networks:
      - woody_net
    deploy:
      restart_policy:
        condition: any
  front:
    image: xdubruille/woody_front:latest
    networks:
      - woody_net
    deploy:
      restart_policy:
        condition: any

  reverse:
    image: xdubruille/woody_rp:latest
    ports:
      - "80:8080"
    depends_on:
      - front
      - api
    networks:
      - woody_net
    deploy:
      restart_policy:
        condition: any
networks:
  woody_net:
    driver: overlay
